compressionLevel: mixed

enableGlobalCache: false

npmMinimalAgeGate: 10080 # A week in minutes
npmPreapprovedPackages:
  - "@openremote/*"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.12.0.cjs
