# IntelliJ's generated JavaExec task is not compatible with Gradle's configuration cache.
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx3g
org.gradle.parallel=true

projectName = fleet-management
version = 1.0-SNAPSHOT

openremoteVersion = 1.30.0

jacksonVersion = 2.21.5
testLoggerVersion = 4.0.0
typescriptGeneratorVersion = 4.1.1


swaggerVersion = 2.2.53
swaggeruiVersion = 5.32.11
