
plugins {
    id 'groovy'
    id 'cz.habarta.typescript-generator'
}

dependencies {
    compileOnly "io.openremote:openremote-model-util:$openremoteVersion"
    implementation project(":agent")
    implementation project(":model")
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:$jacksonVersion"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:$jacksonVersion"
    implementation "com.fasterxml.jackson.module:jackson-module-parameter-names:$jacksonVersion"
    implementation "cz.habarta.typescript-generator:typescript-generator-core:$typescriptGeneratorVersion"
}

generateTypeScript createTSGeneratorConfigForModel("src/model.ts", findProject(":model"))

def generateTypeScriptTask = tasks.named("generateTypeScript") {
    // Work around typescript-generator exposing non-serializable configuration objects as Gradle task inputs.
    doNotTrackState("typescript-generator uses non-serializable task input types")
}

build.dependsOn generateTypeScriptTask, npmBuild
npmBuild.dependsOn generateTypeScriptTask

tasks.named('clean', Delete) {
    delete layout.projectDirectory.dir('dist')
}

tasks.register('prepareUi') {
    dependsOn clean, npmPrepare
}

tasks.register('publishUi') {
    dependsOn clean, npmPublish
}
