# ----------------------------------------------------------------------------------------
# Docker image for populating deployment-data volume with project specific customisations
# ----------------------------------------------------------------------------------------
FROM scratch

RUN mkdir -p /deployment/manager/extensions
ADD image /deployment
